server:
  port: 8761

ead:
  serviceRegistry:
    username: serviceregistry
    password: Senha123

eureka:
  client:
    register-with-eureka: false # Avoid registry like client. Only server
    fetch-registry: false
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761'
